-- StaffReady Scheduler — persistence schema
-- Run this once in the Supabase SQL Editor (Project → SQL Editor → New query).

create table if not exists employees (
  id bigint primary key,
  name text not null,
  type text not null check (type in ('permanent', 'extra')),
  fixed_days int[] not null default '{}',
  allowed_shifts text[] not null default '{}',
  -- Rolling shift-count cap for employees on compressed/extended-hour
  -- schedules, e.g. {"windowDays": 14, "maxShifts": 7} for someone
  -- hitting 80 hours/week on >8hr shifts. Null/absent = no cap
  -- (standard rotation). Permanent employees only.
  shift_cap jsonb,
  -- Weekend rotation cycle, e.g. {"cycleWeekends": 4, "openOffset": 0}
  -- means: of every 4 consecutive weekends, this employee is open to
  -- work exactly 1 (the one at position `openOffset` in the cycle) and
  -- is hard-blocked (PTO-1) on the other 3. cycleWeekends: 2 = every
  -- other weekend. Null = opted out of the rotation entirely (works
  -- every weekend, no auto-blocking). Defaults every employee to the
  -- "one weekend a month" policy; set to null for anyone who opted to
  -- work every weekend, or adjust cycleWeekends for every-other-weekend.
  -- Permanent employees only.
  weekend_rotation jsonb default '{"cycleWeekends": 4, "openOffset": 0}'::jsonb
);

create table if not exists pto_status (
  employee_id bigint not null references employees(id) on delete cascade,
  day_iso date not null,
  status text not null check (status in ('PTO1', 'PTO2')),
  -- Who/what put this entry here. 'weekend_rotation' rows are the ones
  -- auto-generated by applying an employee's weekend rotation cycle —
  -- tagging them lets a re-apply safely replace only its OWN past output
  -- (e.g. after an employee's rotation group changes) without ever
  -- touching anything set manually, including manual edits to a cell
  -- that started out as an auto-generated one.
  source text not null default 'manual' check (source in ('manual', 'weekend_rotation')),
  primary key (employee_id, day_iso)
);

create table if not exists extra_availability (
  employee_id bigint not null references employees(id) on delete cascade,
  day_iso date not null,
  primary key (employee_id, day_iso)
);

create table if not exists holidays (
  day_iso date primary key
);

create table if not exists collapsed_shifts (
  code text primary key
);

create table if not exists saved_schedules (
  id bigint generated always as identity primary key,
  created_at timestamptz not null default now(),
  snapshot jsonb not null
);

-- Row Level Security
-- This app has no login system — it's meant to run locally for a single
-- user/team who holds the anon key. RLS is enabled with permissive
-- policies so the anon key can read/write freely. Do NOT deploy this
-- publicly without adding real auth first, since anyone with the anon
-- key (visible in client JS) could read or modify all rows.
alter table employees enable row level security;
alter table pto_status enable row level security;
alter table extra_availability enable row level security;
alter table holidays enable row level security;
alter table collapsed_shifts enable row level security;
alter table saved_schedules enable row level security;

create policy "anon full access" on employees for all using (true) with check (true);
create policy "anon full access" on pto_status for all using (true) with check (true);
create policy "anon full access" on extra_availability for all using (true) with check (true);
create policy "anon full access" on holidays for all using (true) with check (true);
create policy "anon full access" on collapsed_shifts for all using (true) with check (true);
create policy "anon full access" on saved_schedules for all using (true) with check (true);
